name: Express Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: npm
          registry-url: "https://npm.pkg.github.com"
          scope: "@mle07"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  deploy-main:
    name: Deploy to main
    needs: build
    runs-on: ubuntu-latest
    environment: main

    steps:
      # - name: Publish package
      #   run: npm publish --access retsricted

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
